[project]
name = 'contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.centrifuge-counter]
path = 'contracts/counter.clar'
clarity_version = 4
epoch = 'latest'

[contracts.centrifuge-king-v2]
path = 'contracts/centrifuge-king-v2.clar'
clarity_version = 2
epoch = '2.5'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
